import bcrypt from 'bcryptjs';

// Realistic initial dataset for offline/in-memory resilience
export const mockUsers = [
  {
    _id: 'user_admin_001',
    name: 'System Admin',
    email: 'admin@rentalhub.com',
    password: 'AdminPassword123!', // for mock comparison
    passwordHash: bcrypt.hashSync('AdminPassword123!', 8),
    role: 'Admin',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user_owner_001',
    name: 'Michael Vance',
    email: 'owner@rentalhub.com',
    password: 'OwnerPassword123!',
    passwordHash: bcrypt.hashSync('OwnerPassword123!', 8),
    role: 'Owner',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user_tenant_001',
    name: 'Sarah Jenkins',
    email: 'tenant@rentalhub.com',
    password: 'TenantPassword123!',
    passwordHash: bcrypt.hashSync('TenantPassword123!', 8),
    role: 'Tenant',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    createdAt: new Date().toISOString(),
  },
];

export const mockProperties = [
  {
    _id: 'prop_001',
    title: 'Azure Sky Penthouse with Panoramic Bay Views',
    description: 'Exquisite 3-bedroom luxury penthouse overlooking the waterfront. Features floor-to-ceiling glass windows, private rooftop infinity pool, Italian marble flooring, and smart home automation.',
    location: 'Downtown Waterfront, Miami, FL',
    propertyType: 'Penthouse',
    rentPrice: 3800,
    rentType: 'Monthly',
    bedrooms: 3,
    bathrooms: 3,
    propertySize: 2450,
    amenities: ['WiFi', 'Parking', 'Swimming Pool', 'Gym', 'Air Conditioning', 'Pets Allowed', 'Furnished', 'Balcony'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: 'Private elevator access, 24/7 concierge, Sub-Zero wine cellar.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (305) 555-0192',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    _id: 'prop_002',
    title: 'Modern Minimalist Loft in Tech District',
    description: 'Chic, open-concept urban loft with high ceilings, exposed brick walls, and industrial accents. Walking distance to premier cafes, tech hubs, and metro lines.',
    location: 'Silicon Alley, Austin, TX',
    propertyType: 'Studio',
    rentPrice: 1950,
    rentType: 'Monthly',
    bedrooms: 1,
    bathrooms: 1,
    propertySize: 850,
    amenities: ['WiFi', 'Gym', 'Air Conditioning', 'Furnished', 'Elevator'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: 'Gigabit fiber internet pre-installed, keyless smart lock.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (512) 555-0144',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    _id: 'prop_003',
    title: 'Serene Highland Villa with Private Garden',
    description: 'Charming 4-bedroom sanctuary nestled in peaceful hills. Includes a landscaped private yard, heated pool, gourmet chef kitchen, and dual master suites.',
    location: 'Beverly Hills Foothills, Los Angeles, CA',
    propertyType: 'Villa',
    rentPrice: 5200,
    rentType: 'Monthly',
    bedrooms: 4,
    bathrooms: 4,
    propertySize: 3600,
    amenities: ['WiFi', 'Parking', 'Swimming Pool', 'Air Conditioning', 'Pets Allowed', 'Garden'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: 'Solar panels with backup battery, organic citrus orchard.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (310) 555-0188',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    _id: 'prop_004',
    title: 'Contemporary Waterfront Apartment',
    description: 'Breathtaking 2-bedroom residence featuring hardwood flooring, stainless steel European appliances, and a sun-drenched private terrace overlooking the marina.',
    location: 'Pacific Heights, San Francisco, CA',
    propertyType: 'Apartment',
    rentPrice: 2850,
    rentType: 'Monthly',
    bedrooms: 2,
    bathrooms: 2,
    propertySize: 1250,
    amenities: ['WiFi', 'Parking', 'Gym', 'Air Conditioning', 'Balcony'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502005229762-ee1b2b81e469?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: 'EV charging station in private garage, secured storage unit.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (415) 555-0123',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    _id: 'prop_005',
    title: 'Emerald Grove Suburban Family Residence',
    description: 'Spacious 3-bedroom craftsman home with open floor plan, fireplace, private fenced backyard, and attached two-car garage located near top-rated schools.',
    location: 'Bellevue Suburbs, Seattle, WA',
    propertyType: 'House',
    rentPrice: 2600,
    rentType: 'Monthly',
    bedrooms: 3,
    bathrooms: 2.5,
    propertySize: 2100,
    amenities: ['WiFi', 'Parking', 'Pets Allowed', 'Garden', 'Fireplace'],
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: 'High-efficiency heat pump, walk-in closets in every bedroom.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (206) 555-0177',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    _id: 'prop_006',
    title: 'The Grand View Central Luxury Condo',
    description: 'Upscale corner condo on the 18th floor offering stunning skyline panoramas, custom Italian cabinetry, quartz countertops, and dedicated valet service.',
    location: 'Midtown Manhattan, New York, NY',
    propertyType: 'Condo',
    rentPrice: 4200,
    rentType: 'Monthly',
    bedrooms: 2,
    bathrooms: 2,
    propertySize: 1400,
    amenities: ['WiFi', 'Gym', 'Air Conditioning', 'Furnished', 'Elevator', 'Security System'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80'
    ],
    extraFeatures: '24/7 doorman, resident sky lounge, steam room & sauna.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (212) 555-0111',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_007',
    title: 'Historic Brick Loft with Skylight',
    description: 'Character-filled artist loft with exposed timber beams and oversized windows.',
    location: 'Old Town, Chicago, IL',
    propertyType: 'Apartment',
    rentPrice: 2100,
    rentType: 'Monthly',
    bedrooms: 1,
    bathrooms: 1,
    propertySize: 950,
    amenities: ['WiFi', 'Air Conditioning', 'Elevator'],
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Original 1920s pine wood floors.',
    status: 'Pending',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (312) 555-0189',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_008',
    title: 'Mountain Retreat Cabin with Hot Tub',
    description: 'Cozy alpine cabin offering tranquility and forest views.',
    location: 'Aspen Highlands, CO',
    propertyType: 'House',
    rentPrice: 4500,
    rentType: 'Monthly',
    bedrooms: 3,
    bathrooms: 2,
    propertySize: 1800,
    amenities: ['WiFi', 'Parking', 'Fireplace'],
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Ski-in / ski-out trail access.',
    status: 'Rejected',
    rejectionFeedback: 'The property documentation requires municipal permit verification and higher resolution exterior photographs.',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (970) 555-0165',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_009',
    title: 'Pacific Coast Oceanview Penthouse',
    description: 'Breathtaking 3-bedroom luxury penthouse perched right on the bluffs of Malibu. Features panoramic floor-to-ceiling glass windows, wrapping private terrace, chef gourmet kitchen, and private elevator.',
    location: 'Malibu Bluffs, Malibu, CA',
    propertyType: 'Penthouse',
    rentPrice: 4600,
    rentType: 'Monthly',
    bedrooms: 3,
    bathrooms: 3,
    propertySize: 2200,
    amenities: ['WiFi', 'Parking', 'Swimming Pool', 'Air Conditioning', 'Balcony', 'Furnished', 'Elevator'],
    images: ['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Direct private beach staircase, sunset observation deck.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (310) 555-0199',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_010',
    title: 'Chic Historic Brownstone Residence',
    description: 'Classic Victorian architectural masterpiece located in the quiet historic district. Restored parquet flooring, ornate fireplaces, stained glass windows, and private brick-paved courtyard.',
    location: 'Back Bay, Boston, MA',
    propertyType: 'House',
    rentPrice: 3200,
    rentType: 'Monthly',
    bedrooms: 3,
    bathrooms: 2.5,
    propertySize: 1950,
    amenities: ['WiFi', 'Parking', 'Pets Allowed', 'Garden', 'Furnished', 'Security System'],
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Sub-Zero refrigeration, custom library with built-in shelving.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (617) 555-0145',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_011',
    title: 'Skyline Panorama Highrise Condo',
    description: 'Ultra-modern 34th floor residence overlooking the city skyline. Contemporary minimalist design, automated blackout shades, Italian marble bathrooms, and 24/7 concierge security.',
    location: 'Loop Financial Center, Chicago, IL',
    propertyType: 'Condo',
    rentPrice: 2900,
    rentType: 'Monthly',
    bedrooms: 2,
    bathrooms: 2,
    propertySize: 1350,
    amenities: ['WiFi', 'Gym', 'Air Conditioning', 'Elevator', 'Security System', 'Balcony'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Heated indoor lap pool and sky deck access.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (312) 555-0176',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_012',
    title: 'Rustic Alpine Mountain Chalet',
    description: 'Authentic handcrafted timber chalet surrounded by majestic pines. Soaring cathedral ceilings, floor-to-ceiling stone fireplace, private outdoor cedar hot tub, and ski storage.',
    location: 'Vail Mountain Village, Vail, CO',
    propertyType: 'Villa',
    rentPrice: 4800,
    rentType: 'Monthly',
    bedrooms: 4,
    bathrooms: 3.5,
    propertySize: 3100,
    amenities: ['WiFi', 'Parking', 'Fireplace', 'Pets Allowed', 'Furnished', 'Garden'],
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Heated driveway, private dry cedar sauna.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (970) 555-0122',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_013',
    title: 'Urban Industrial Artist Loft',
    description: 'Sprawling creative sanctuary in a renovated 19th-century textile warehouse. Exposed brick masonry, 14-foot timber beam ceilings, polished concrete floors, and northern artist light.',
    location: 'SoHo Design District, New York, NY',
    propertyType: 'Studio',
    rentPrice: 2400,
    rentType: 'Monthly',
    bedrooms: 1,
    bathrooms: 1,
    propertySize: 1100,
    amenities: ['WiFi', 'Air Conditioning', 'Elevator', 'Furnished'],
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Acoustic soundproofing, commercial-grade induction range.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (212) 555-0185',
    },
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prop_014',
    title: 'Sunny Tropical Beachside Oasis',
    description: 'Idyllic coastal villa just footsteps away from warm sandy shores. Tropical courtyard garden, plunge pool, outdoor summer kitchen, and open breezes through French louver doors.',
    location: 'South Beach, Miami Beach, FL',
    propertyType: 'Villa',
    rentPrice: 5500,
    rentType: 'Monthly',
    bedrooms: 4,
    bathrooms: 4,
    propertySize: 3400,
    amenities: ['WiFi', 'Parking', 'Swimming Pool', 'Air Conditioning', 'Pets Allowed', 'Balcony', 'Garden'],
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80'],
    extraFeatures: 'Private boat dock slip, outdoor shower.',
    status: 'Approved',
    rejectionFeedback: '',
    owner: {
      ownerId: 'user_owner_001',
      name: 'Michael Vance',
      email: 'owner@rentalhub.com',
      phone: '+1 (305) 555-0133',
    },
    createdAt: new Date().toISOString(),
  },
];

export const mockReviews = [
  {
    _id: 'rev_001',
    propertyId: 'prop_001',
    tenantId: 'user_tenant_001',
    name: 'Sarah Jenkins',
    email: 'sarah.j@gmail.com',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    comment: 'Staying at Azure Sky Penthouse was an absolute dream! The bay views at sunset are unbeatable and the amenities made working remotely effortless.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    _id: 'rev_002',
    propertyId: 'prop_002',
    tenantId: 'user_tenant_001',
    name: 'David Chen',
    email: 'david.chen@techmail.io',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    comment: 'Super fast internet, impeccably clean, and the location in Silicon Alley saved me 30 minutes of commute every morning. 10/10 recommendation!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    _id: 'rev_003',
    propertyId: 'prop_003',
    tenantId: 'user_tenant_001',
    name: 'Elena Rostova',
    email: 'elena.rostova@luxuryliving.org',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    comment: 'The villa exceeded every expectation. Private garden was stunning and the owner Michael was extremely attentive and accommodating.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    _id: 'rev_004',
    propertyId: 'prop_004',
    tenantId: 'user_tenant_001',
    name: 'Marcus Brody',
    email: 'mbrody@designlab.com',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    rating: 5,
    comment: 'Booking and paying via Stripe was fast and hassle-free. The waterfront apartment looks exactly like the high-res photos. Will definitely book again!',
    createdAt: new Date().toISOString(),
  },
];

export const mockBookings = [
  {
    _id: 'book_001',
    propertyId: 'prop_001',
    propertyName: 'Azure Sky Penthouse with Panoramic Bay Views',
    propertyImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Downtown Waterfront, Miami, FL',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-10-01').toISOString(),
    contactNumber: '+1 (555) 019-9231',
    additionalNotes: 'Requesting garage parking access.',
    amountPaid: 3800,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample001',
    createdAt: new Date('2026-02-15').toISOString(),
  },
  {
    _id: 'book_002',
    propertyId: 'prop_002',
    propertyName: 'Modern Minimalist Loft in Tech District',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Silicon Alley, Austin, TX',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-03-15').toISOString(),
    contactNumber: '+1 (555) 012-3456',
    additionalNotes: 'Late arrival expected.',
    amountPaid: 1950,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample002',
    createdAt: new Date('2026-03-10').toISOString(),
  },
  {
    _id: 'book_003',
    propertyId: 'prop_003',
    propertyName: 'Serene Highland Villa with Private Garden',
    propertyImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Beverly Hills Foothills, Los Angeles, CA',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-04-01').toISOString(),
    contactNumber: '+1 (555) 014-4321',
    additionalNotes: 'Family vacation stay.',
    amountPaid: 5200,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample003',
    createdAt: new Date('2026-03-25').toISOString(),
  },
  {
    _id: 'book_004',
    propertyId: 'prop_004',
    propertyName: 'Contemporary Waterfront Apartment',
    propertyImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Pacific Heights, San Francisco, CA',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-05-10').toISOString(),
    contactNumber: '+1 (555) 018-8765',
    additionalNotes: 'Corporate executive lease.',
    amountPaid: 2850,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample004',
    createdAt: new Date('2026-05-02').toISOString(),
  },
  {
    _id: 'book_005',
    propertyId: 'prop_005',
    propertyName: 'Emerald Grove Suburban Family Residence',
    propertyImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Bellevue Suburbs, Seattle, WA',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-06-01').toISOString(),
    contactNumber: '+1 (555) 017-7654',
    additionalNotes: 'Pet deposit included.',
    amountPaid: 2600,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample005',
    createdAt: new Date('2026-05-20').toISOString(),
  },
  {
    _id: 'book_006',
    propertyId: 'prop_006',
    propertyName: 'The Grand View Central Luxury Condo',
    propertyImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Midtown Manhattan, New York, NY',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-07-05').toISOString(),
    contactNumber: '+1 (555) 015-5432',
    additionalNotes: 'Keyless entry requested.',
    amountPaid: 4200,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample006',
    createdAt: new Date('2026-06-28').toISOString(),
  },
  {
    _id: 'book_007',
    propertyId: 'prop_001',
    propertyName: 'Azure Sky Penthouse with Panoramic Bay Views',
    propertyImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Downtown Waterfront, Miami, FL',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-08-15').toISOString(),
    contactNumber: '+1 (555) 019-9876',
    additionalNotes: 'Summer holiday reservation.',
    amountPaid: 3800,
    bookingStatus: 'Approved',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample007',
    createdAt: new Date('2026-08-01').toISOString(),
  },
  {
    _id: 'book_008',
    propertyId: 'prop_002',
    propertyName: 'Modern Minimalist Loft in Tech District',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    propertyLocation: 'Silicon Alley, Austin, TX',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerEmail: 'owner@rentalhub.com',
    moveInDate: new Date('2026-09-20').toISOString(),
    contactNumber: '+1 (555) 012-2109',
    additionalNotes: 'Fall quarter reservation.',
    amountPaid: 1950,
    bookingStatus: 'Pending',
    paymentStatus: 'Paid',
    paymentIntentId: 'pi_3L7xsample008',
    createdAt: new Date('2026-09-02').toISOString(),
  },
];

export const mockTransactions = [
  {
    _id: 'tx_001',
    transactionId: 'TXN_20260215_001',
    bookingId: 'book_001',
    propertyId: 'prop_001',
    propertyName: 'Azure Sky Penthouse with Panoramic Bay Views',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 3800,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-02-15').toISOString(),
  },
  {
    _id: 'tx_002',
    transactionId: 'TXN_20260310_002',
    bookingId: 'book_002',
    propertyId: 'prop_002',
    propertyName: 'Modern Minimalist Loft in Tech District',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 1950,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-03-10').toISOString(),
  },
  {
    _id: 'tx_003',
    transactionId: 'TXN_20260325_003',
    bookingId: 'book_003',
    propertyId: 'prop_003',
    propertyName: 'Serene Highland Villa with Private Garden',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 5200,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-03-25').toISOString(),
  },
  {
    _id: 'tx_004',
    transactionId: 'TXN_20260502_004',
    bookingId: 'book_004',
    propertyId: 'prop_004',
    propertyName: 'Contemporary Waterfront Apartment',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 2850,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-05-02').toISOString(),
  },
  {
    _id: 'tx_005',
    transactionId: 'TXN_20260520_005',
    bookingId: 'book_005',
    propertyId: 'prop_005',
    propertyName: 'Emerald Grove Suburban Family Residence',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 2600,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-05-20').toISOString(),
  },
  {
    _id: 'tx_006',
    transactionId: 'TXN_20260628_006',
    bookingId: 'book_006',
    propertyId: 'prop_006',
    propertyName: 'The Grand View Central Luxury Condo',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 4200,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-06-28').toISOString(),
  },
  {
    _id: 'tx_007',
    transactionId: 'TXN_20260801_007',
    bookingId: 'book_007',
    propertyId: 'prop_001',
    propertyName: 'Azure Sky Penthouse with Panoramic Bay Views',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 3800,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-08-01').toISOString(),
  },
  {
    _id: 'tx_008',
    transactionId: 'TXN_20260902_008',
    bookingId: 'book_008',
    propertyId: 'prop_002',
    propertyName: 'Modern Minimalist Loft in Tech District',
    tenantId: 'user_tenant_001',
    tenantName: 'Sarah Jenkins',
    tenantEmail: 'tenant@rentalhub.com',
    ownerId: 'user_owner_001',
    ownerName: 'Michael Vance',
    ownerEmail: 'owner@rentalhub.com',
    amount: 1950,
    paymentMethod: 'Stripe',
    createdAt: new Date('2026-09-02').toISOString(),
  },
];

export const mockFavorites = [];
